### ISSUE TITLE
Why ignore /bin/ directory for Ruby project?

### ISSUE THREAD

**Issue by ebukaume** [microverseinc/linters-config#24]
With reference to this block of code: 

https://github.com/microverseinc/linters-config/blob/41fa522c164c3d9933da0c20a565d079faba915e/ruby/.stickler.yml#L9-L16
[source](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)

https://github.com/microverseinc/linters-config/blob/41fa522c164c3d9933da0c20a565d079faba915e/ruby/.rubocop.yml#L1-L7
[source](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml)

The `bin` directory contains codes that should be lint. For example, in the Tic Tac Toe project, we put our `main.rb` in that folder. So ignoring that directory means we could write dirty codes and get away with it.

I suggest we not ignore the `/bin/`. directory for the Ruby section.

**Comment by shloch** [comment]
@ebukaume i think that's because when configuring this file, that `bin/` folder in the config file is the one in a RAILS project (in this case, this will make sense), not the one in a regular Ruby project(which aligns with your comment). 

Maybe we'll need separate `.rubocop.yml` file for RAILS vs regular RUBY projects (working on that)

**Comment by ebukaume** [comment]
Yes, @shloch that's what the issue report is about. Perhaps I should have made it clearer. Thanks for making it clearer.

**Comment by nidalaa** [comment]
Thank you for your input @ebukaume and @shloch - the issues has been solved in thin PR https://github.com/microverseinc/linters-config/pull/29. 💃
