### ISSUE TITLE
.rubocop.yml throws console warnings in the rubocop version 0.80.1

### ISSUE THREAD

**Issue by men32z** [microverseinc/linters-config#56]
Adding this removes the warning but I don't know if this matches the microverse community standards.
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false

**Comment by men32z** [comment]
also adding those lines will throw an error in stickler online check 
`Error: unrecognized cop Style/HashEachMethods found in .rubocop.yml, unrecognized cop Style/HashTransformKeys found in .rubocop.yml, unrecognized cop Style/HashTransformValues found in .rubocop.yml`

**Comment by MauricioRobayo** [comment]
Hi @men32z  and thanks for opening the issue!

Have you seen this: https://github.com/rubocop-hq/rubocop/issues/7731#issuecomment-588090599

Seems like Stickler might not be running the latest version of Rubocop, if I test your configuration with v0.79 it throws the error you mentioned.

Since it is only an informative message starting from Rubocop >0.80 and not a warning, might not be a real issue. What do you think?

**Comment by men32z** [comment]
Yes, Thank you Mauricio, I'm going to close this issue.
