### ISSUE TITLE
Unable to resolve path to module .." (import/no-unresolved)

### ISSUE THREAD

**Issue by OlukaDenis** [microverseinc/linters-config#66]
I'm getting this linter error while using `import '@fortawesome/fontawesome-free/js...`.
After doing some research on it, many solutions solved it by adding ` "import/no-unresolved": "off"` to the `.eslintrc` file. 
May you have a look at it because I'm stuck with my project.
If it is okay I can create PR for it.

Thanks

**Comment by MauricioRobayo** [comment]
Hi @OlukaDenis, thanks for raising this issue.

It is OK to disable some rules when there is no way around it, but please don't do it on your `.esling.config.js`, just add a disable comment next to the line you want to disable ESLint with the specific rule you want to disable:

https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

So, in your case, you can add the following comment above the offending line:

```js
// eslint-disable-next-line no-unresolved
import '@fortawesome/fontawesome-free/js...';
```

Doing it this way makes it clear you are making a valid choice there because there is no way around, and you don't have to modify the ESLint configuration provided. If you disable it on the whole file with a comment, or on the ESLint configuration, then it won't be clear why you are disabling it and if it is a valid choice to do it.

Please let me know if this works for you.

**Comment by MauricioRobayo** [comment]
Sorry, I close it by accident 😄 .

**Comment by OlukaDenis** [comment]
Well, It has worked. Thank you!
