### ISSUE TITLE
Update check-linters-config script with new configs

### ISSUE THREAD

**Issue by jubaan** [microverseinc/linters-config#84]
#  Update check-linters-config script with new configs

## Description of issue

Great tool but seems like it's not updated for the todays linter requirements. 

[check-linters-config](https://github.com/microverseinc/linters-config/blob/master/scripts/check-linters-conf.sh) looks for ".stickel.yml" but is not needed anymore for the whole curriculum. It should look for `.stylelinterrc.json`, `.hintrc`, `.rubocop.yml` , `.eslintrc.json` instead.

## Proposed solution

- change directory from `css` to `html-css`
https://github.com/microverseinc/linters-config/blob/ac2ce372347629abe53dbeeb34b50a4791aa708f/scripts/check-linters-conf.sh#L11

- Remove `.styckler.yml` from all files to be checked and replace with other new config files
```diff
case $1 in
  html-css)
-  config_files=(".stickler.yml" "stylelint.config.js")
+  config_files=(".hintrc" ".stylelintrc.json")
  ;;
-  ruby | ror)
+  ruby)
-  config_files=(".stickler.yml" ".rubocop.yml")
+  config_files=(".rubocop.yml")
  ;;
+  ror)
+  config_files=(".stylelintrc.json" ".rubocop.yml")
+  ;;
  javascript | react-redux)
-  config_files=(".stickler.yml" ".eslintrc.json")
+  config_files=(".stylelintrc.json" ".eslintrc.json")
  ;;
  *)
  echo "$usage"
  exit 1
esac
```

**Comment by shshamim63** [comment]
Hi @jubaan :wave: 
I tried to get the overall idea but I could not fetch it. Would you like to provide more information, please?

**Comment by bolah2009** [comment]
@shshamim63, I believe this is the tool @jubaan is talking about https://github.com/microverseinc/linters-config/tree/master/scripts

@shshamim63 Let's use this issue to fix this. 

Since `.styckler.yml` is no more required, the script should not check for it anymore. Currently, this may result in errors.

## Possible solution

- change directory from `css` to `html-css`
https://github.com/microverseinc/linters-config/blob/ac2ce372347629abe53dbeeb34b50a4791aa708f/scripts/check-linters-conf.sh#L11

- Remove `.styckler.yml` from all files to be checked and replace with other new config files
```diff
case $1 in
  html-css)
-  config_files=(".stickler.yml" "stylelint.config.js")
+  config_files=(".hintrc" ".stylelintrc.json")
  ;;
-  ruby | ror)
+  ruby)
-  config_files=(".stickler.yml" ".rubocop.yml")
+  config_files=(".rubocop.yml")
  ;;
+  ror)
+  config_files=(".stylelintrc.json" ".rubocop.yml")
+  ;;
  javascript | react-redux)
-  config_files=(".stickler.yml" ".eslintrc.json")
+  config_files=(".stylelintrc.json" ".eslintrc.json")
  ;;
  *)
  echo "$usage"
  exit 1
esac
```


@jubaan thanks for opening this issue!

**Comment by bolah2009** [comment]
I updated the issue name and description too, to make it clear.

**Comment by krys2fa** [comment]
Hi @bolah2009, I'd like to give this a try. 😉

**Comment by bolah2009** [comment]
Thanks, @krys2fa, have assigned it to you

**Comment by krys2fa** [comment]
Great. I'll put in a pull request soon @bolah2009.
